### ISSUE TITLE
Connecting Events

### ISSUE THREAD

**Issue by afrittoli** [cdevents/spec#104]
The overarching issue that links the different streams of work about connecting events.

Design document: https://hackmd.io/-Or6hobHSLWVj4duAWX7nA

Related issues:
- https://github.com/cdevents/spec/issues/10
- https://github.com/cdevents/spec/issues/100

**Comment by afrittoli** [comment]
The use case proposed in #142 about the relationship between parent and child pipelines is related to this proposal too. A solid mechanism for connecting events should help event-driven pipeline users manage complex workflows through events.
@xibz ^^^

**Comment by afrittoli** [comment]
PR by @xibz to address this https://github.com/cdevents/spec/pull/139

**Comment by e-backmark-ericsson** [comment]
Closing this as it is mostly implemented by #139 , and the rest will be discussed in #10
