### ISSUE TITLE
[doc] better to add sample json for each event in the documentation

### ISSUE THREAD

**Issue by larrycai** [cdevents/spec#108]
Try to write some applications to send cdevents via cloudevents, but it is really difficult to find sample event in json. (even in sdk repo)

scheme is good to define the event, and sample json can help end-user to understand and use the cdevents

so please help to add samples how the cdevents look like in json format for cdevents like https://github.com/cloudevents/spec/blob/main/cloudevents/formats/json-format.md

**Comment by afrittoli** [comment]
Hello @larrycai, thank you for your interest in CDEvents and for the feedback on the documentation.
It would be nice indeed to have examples for each event type. 

In the meanwhile, this [one example](https://github.com/cdevents/spec/blob/v0.1.1/cloudevents-binding.md#examples) might help.

Would you be interested in helping us build those examples?

**Comment by larrycai** [comment]
I am new to cdevents, can't contribute so far.

And the example seems strange to me, it does not follow cloudevents spec ;-), I feel it shall be somethings like below to make it complete.  

````
POST /sink HTTP/1.1
Host: cdevents.example.com
ce-specversion: 1.0
ce-type: dev.cdevents.taskrun.started.0.1-draft
ce-time: 2018-04-05T17:31:00Z
ce-id: A234-1234-1234
ce-source: /staging/tekton/
ce-subject: /namespace/taskrun-123
Content-Type: application/json; charset=utf-8
Content-Length: nnnn

"specversion": "1.0",
"id": "2277f77c-ae9b-48d7-9a0e-e5424b38c98f",
"source": "cdevent.demo.url",
"type": "cdevents",
"time": "2023-01-25T07:35:27.788539+00:00",
 "data": {
       "context": {
          "version" : "0.1.1",
          "id" : "A234-1234-1234",
          "source" : "/staging/tekton/",
          "type" : "dev.cdevents.taskrun.started",
          "timestamp" : "2018-04-05T17:31:00Z",
       }
       "subject" : {
          "id": "/namespace/taskrun-123",
          "type": "taskRun",
          "content": {
             "task": "my-task",
             "url": "/apis/tekton.dev/v1beta1/namespaces/default/taskruns/my-taskrun-123"
             "pipelineRun": {
                "id": "/somewherelse/pipelinerun-123",
                "source": "/staging/jenkins/"
             }
          }
       }
    }
````

`cdevents` is the payload inside cloudevents, so in http layer, it is embedded into `data`, just comments, I not so sure

**Comment by e-backmark-ericsson** [comment]
@afrittoli , we should also include a validation of all example files towards the current event schemas, as part of the workflow running on each new commit towards main.

**Comment by afrittoli** [comment]
Hello @larrycai - we implemented examples for all events now - see https://github.com/cdevents/spec/tree/main/examples
The example are tested against the schema as part of CI.
Do you consider these examples enough to close this issue?
