### ISSUE TITLE
The old schema $id references are not valid anymore

### ISSUE THREAD

**Issue by e-backmark-ericsson** [cdevents/spec#110]
The $id references in the json schemas for the events are not valid anymore since the rendering of cdevents.dev was changed recently.

Example: 
This event schema: https://github.com/cdevents/spec/blob/spec-v0.1/schemas/artifactpackaged.json
has an $id reference to https://cdevents.dev/0.1.2/schema/artifact-packaged-event
which is not valid

**Comment by afrittoli** [comment]
Fixed by https://github.com/cdevents/cdevents.dev/pull/33
