### ISSUE TITLE
The usage of URL, URI and URI-reference is not aligned

### ISSUE THREAD

**Issue by e-backmark-ericsson** [cdevents/spec#114]
As noted in [this comment](https://github.com/cdevents/spec/pull/107#discussion_r1099908999), our usage of universal resource locators/references is not really aligned over our json schemas and markdown docs. We should decide on what format to use and then make sure it is updated in the relevant files

**Comment by afrittoli** [comment]
I don't think there is any misalignment in the usage of URI and URI refs - however, the JSON schema does not enforce URI/URI-ref yet. This is only because I didn't realise it was possible in jsonschema - I will add it as part of this issue.

**Comment by afrittoli** [comment]
Discussed this item in the WG:
- URI-reference is a superset of URI
- For now (v0.2) we may keep URI-reference and indicate in the spec that URI is preferred where available

**Comment by afrittoli** [comment]
We already indicate URI as the recommended format:

> #### source (context)
>
>  - Type: [`URI-Reference`][typesystem]
     - Description: defines the context in which an event happened. The main purpose
       of the source is to provide global uniqueness for [`source`](#source-context) +
       [`id`](#id-context). 
>
>     (...)
>  - Constraints:
    - REQUIRED
    - MUST be a non-empty URI-reference
    - An absolute URI is RECOMMENDED

**Comment by afrittoli** [comment]
Fixed by #116
