### ISSUE TITLE
The artifact subject.change field is not documented explicitly

### ISSUE THREAD

**Issue by e-backmark-ericsson** [cdevents/spec#115]
The subject `artifact` has the field `change` according to this table: https://github.com/cdevents/spec/blob/main/continuous-integration-pipeline-events.md#artifact, but it is not described as a valid field for any of its event descriptions: https://github.com/cdevents/spec/blob/main/continuous-integration-pipeline-events.md#artifact-packaged
It is a required field according to the artifact.packaged schema: https://github.com/cdevents/spec/blob/main/schemas/artifactpackaged.json#L56

**Comment by afrittoli** [comment]
Thanks @e-backmark-ericsson - it should indeed be documented in the artifact packaged table, I will fix that
