### ISSUE TITLE
CDEvents Whitepaper incorrect link

### ISSUE THREAD

**Issue by agardnerIT** [cdevents/spec#127]
The [CDEvents whitepaper](https://github.com/cdevents/spec/blob/main/CDEvents_Whitepaper.pdf) contains a link to `Continuous Deployment Pipeline Events` which **should** link to [here](https://github.com/cdfoundation/sig-events/blob/main/vocabulary-draft/continuous-deployment-pipeline-events.md). Instead it links to the [CI events spec](https://github.com/cdfoundation/sig-events/blob/main/vocabulary-draft/continuous-integration-pipeline-events.md).

Ie. Link is `https://github.com/cdfoundation/sig-events/blob/main/vocabulary-draft/continuous-integration-pipeline-events.md`

But should be `https://github.com/cdfoundation/sig-events/blob/main/vocabulary-draft/continuous-deployment-pipeline-events.md`

<img width="473" alt="image" src="https://user-images.githubusercontent.com/26523841/234757917-412bc3ef-9399-4369-b298-7e5e9f69fe01.png">

Tagging @afrittoli as it seems they are the owner.

LMK where I make this change and I'm happy to create a PR.

**Comment by afrittoli** [comment]
Thank you @agardnerIT, nice catch. 
We just updated the whitepaper and we'll be publishing the updated PDF to the website once it's finalised.

**Comment by elmsdata** [comment]
Our company is hosting an open source workshop to help developers with their first contributions to an open source project! If no one else would like to work on this before May 16-17 then we would love to help with this issue. Thanks!

**Comment by swapnil-d-gawai** [comment]
Hi, I will work on this shortly as part of the workshop of May 16 - 17.
