### ISSUE TITLE
Link to examples in mardown docs

### ISSUE THREAD

**Issue by afrittoli** [cdevents/spec#129]
We do have [examples](https://github.com/cdevents/spec/blob/main/examples/) in the spec repo now, but they may not be easy to discover, we should link to individual examples from the respective chapter in the spec

**Comment by elmsdata** [comment]
Hey @afrittoli and happy Friday! Our company is hosting an open source workshop on May 16-17 and looking for issues in CD Events project that would be a great first issues for developers to learn about the contribution process! If no one else would like to work on this before then we would love to try and help with this issue. Thanks!

**Comment by e-backmark-ericsson** [comment]
@elmsdata , that's a great proposal!

**Comment by austenadler** [comment]
I will work on this issue if it not complete by 16-17 May (I am with @elmsdata)

**Comment by swapnil-d-gawai** [comment]
I will work on this issue as part of the May 16-17 workshop.
