### ISSUE TITLE
Nominated Ben Powell as spec maintainer

### ISSUE THREAD

**Issue by afrittoli** [cdevents/spec#175]
I would like to nominate Ben Powell (@xibz) as spec maintainer.

Ben has been a regular contributor for CDEvents working groups for a large fraction of the CDEvents project life.
He contributed the CDEvents links feature, which is now very close to merge, and he worked on the ticket events design as well.

Thank you Ben!

- [x] [PR for codeowners update](https://github.com/cdevents/spec/pull/174)
- [x] Add Ben to the [spec-maintainers](https://github.com/orgs/cdevents/teams/spec-maintainers) team

[Process reference](https://github.com/cdevents/community/blob/main/processes.md)

**Comment by e-backmark-ericsson** [comment]
I would gladly welcome Ben as a maintainer of the CDEvents spec repo. Consider this nomination approved! :)

**Comment by afrittoli** [comment]
@xibz I invited you to the GitHub team, please accept the invite and thanks for all your contributions!! 🎉

**Comment by afrittoli** [comment]
> @xibz I invited you to the GitHub team, please accept the invite and thanks for all your contributions!! 🎉

Invite was accepted, closing the issue.
