### ISSUE TITLE
inconsistent or confusing cloudevent type mapping in cloudevents-binding spec

### ISSUE THREAD

**Issue by strangemonad** [cdevents/spec#178]
The [cloudevents-binding spec](https://github.com/cdevents/spec/blob/v0.3.0/cloudevents-binding.md) states that the cloudevent type must be set to the cdevent type but then the included HTTP example has a mismatch between the `ce-type: dev.cdevents.taskrun.started.0.1-draft` header and the data's `"context"."type":"dev.cdevents.taskrun.started"` field.

**Comment by afrittoli** [comment]
Thanks @strangemonad for reporting this, that is indeed an oversight, I will make a PR to fix it.
