### ISSUE TITLE
Shall we remove the `Run` part from pipeline, task and run events?

### ISSUE THREAD

**Issue by afrittoli** [cdevents/spec#207]
In v0.3 we renamed test events to `TestRun` and `TestSuiteRun` to be consistent with `TaskRun` and `PipelineRun`.

In the context of the [conversation with the OTEL community](https://github.com/open-telemetry/semantic-conventions/issues/915#issuecomment-2079371881), it has been suggested that the `Run` part adds little value, makes names longer, and is not aligned with the name most tools use. The execution use case is by far the most common for observability purposes, and the extra `Run` seems redundant in that context.

We don't have events specific to the creation, update and deletion of pipeline, task and test definition today. If we decided to introduce them in future, they could use a different name, e.g. `PipelineDefinition` or `PipelineTemplate`, or they could be implemented as additional predicates for the same subjects.

Since we're collecting breaking changes for v0.5, if we do change this, it would be good to do it now, so that we might start planning for a 1.0 then.

**Comment by olensmar** [comment]
I personally think the additional clarity provided by the "Run" suffix is worth the 3 bytes it adds - users who are new to CDEvents will likely have an easier time understanding what these events actually represent vs if they are just called `Task`, `Pipeline`, etc.. 

I do agree that naming-alignment can be important if it's with something used in the same context or for the same purpose - not sure that applies to OTEL though!?

**Comment by afrittoli** [comment]
Thanks @olensmar. 

The context with OTEL is that their community is in the process of defining semantics for pipeline observability, and we would like their work and CDEvents to be aligned as much as possible. 

At the working group meeting, the general opinion was that some kind of mapping between CDEvents and OTEL semantics will be required anyway, so we should keep the `Run` part as it is today. 

Based on the input from the CDEvents community, I'm closing this now.
