### ISSUE TITLE
DNS Domain for cdevents

### ISSUE THREAD

**Issue by afrittoli** [cdevents/spec#21]
The project defines a specification for continuous delivery events on top of CloudEvents. 
CloudEvents event types must be in the format `<reverse-dns-domain>.something.something`. 

We’d like to define events type like:

```
cd.events.pipeline.started
cd.events.artifact.published
```

which means we’d need the DNS domain `events.cd` to be owned by the project, or at least owned by the CDF and assigned to the project. We would also like to use the same domain `events.cd` to host a website for the project.

- [x] Domain is provisioned: cdevents.dev available in netlify
- [x] Website setup: https://cdevents.dev
- [x] Documentation updated https://github.com/cdevents/spec/pull/25
- [x] SDKs updated -> tracked through dedicated issues

**Comment by afrittoli** [comment]
Update - it looks like `.cd` domains may be harder to get, while we could get `cdevents.dev` right away. Any thoughts? We would have to change the event types, but since it’s all draft, it shouldn’t be an issue.

**Comment by afrittoli** [comment]
`cdevents.dev` has been registered for us and it's managed via netlify.
A new repo `github.com/cdevents/cdevents.dev` has been created to host the website.

**Comment by afrittoli** [comment]
We discussed during the WG and agreed on using `cdevents.dev`

**Comment by e-backmark-ericsson** [comment]
@afrittoli , this issue could be closed right?
