### ISSUE TITLE
Links not added for new testcase and ticket events in v0.4.0

### ISSUE THREAD

**Issue by rjalander** [cdevents/spec#210]
Embedded links, schemaUri and schemaUri not updated for schemas `testcaserunskipped.json,` `ticketclosed.json`, `ticketcreated.json` and `ticketupdated.json ` in `context/properties`

**Comment by afrittoli** [comment]
Thanks @rjalander, good catch! This is something we need to fix in a `v0.4.1`

**Comment by afrittoli** [comment]
Fixed by https://github.com/cdevents/spec/pull/230
