### ISSUE TITLE
Replace absolute path by relative path in $ref

### ISSUE THREAD

**Issue by davidB** [cdevents/spec#214]
Links introduce references with an absolute path like `"$ref": "/schema/links/embeddedlinksarray.json"`. They are resolved into `https://cdevents.dev/schema/links/embeddedlinksarray.json` (or into a local absolute file path)

- this resolution is invalid (the URL doesn't exist)
- it requires some hack into jsonschema resolver (see https://github.com/cdevents/sdk-rust/blob/4f696866e03eb6d7ee4cebcd86513e6cff6085df/cdevents-sdk/tests/specs.rs#L56)
- it doesn't work with the spec versioning (folder on HTTP or local)

Suggestion: use relative path like `"$ref": "./links/embeddedlinksarray.json"` as this reference is used by jsonschema sibling to the `links` folder.

**Comment by afrittoli** [comment]
Thanks @davidB - this is indeed an issue and we are working on a v0.4.1 to fix that. 
This issue is tracked in #211 already, so closing this as duplicate.
