### ISSUE TITLE
Linters are only ran on main

### ISSUE THREAD

**Issue by xibz** [cdevents/spec#224]
With all the efforts being put into linters and cherry picking them to other branches, I noticed that none of them were being ran.

https://github.com/cdevents/spec/pull/223

While it isn't too big of a deal not having any linting on the cherry pick branches, but since it's easy enough to turn on and will ensure consistency between the pick branches vs main, I would opt to turn them on.

**Comment by xibz** [comment]
https://github.com/cdevents/spec/pull/221 fixes this

**Comment by afrittoli** [comment]
On the `spec-v0.4` branch this is fixed by #220
