### ISSUE TITLE
Clarify versioning of CDEvents spec and events

### ISSUE THREAD

**Issue by afrittoli** [cdevents/spec#32]
Follow up to the discussion in https://github.com/cdevents/spec/pull/30#discussion_r817818324 

We should clarify whether to we want to version events individually or not and what does that mean in terms of compliance to the spec for producers and consumers.

**Comment by m-linner-ericsson** [comment]
We might want to include something like following text as requirement for the version.

> MUST be the version of the event/spec used for producing the event

**Comment by afrittoli** [comment]
Closing in favour of #43
