### ISSUE TITLE
[Nominations Open] CDEvents Most Valuable Contributor Award 2022 🏆

### ISSUE THREAD

**Issue by afrittoli** [cdevents/spec#33]
This issue is to receive nominations for the CDEvents Most Valuable Contributor (MVC) Award 2022.

This award recognizes excellence of contributions to the CDEvents project, which may be any or a combination of contributions to the specification, work on the SDKs, implementation of proofs of concepts, advocacy and fostering adoption in other communities.

To nominate someone, reply to this issue with the following:

Full name of the person you’re nominating
Short description of their contributions to the CDEvents project and why they should win.
Nomination Deadline: Tuesday, April 11, 2022

You may "vote" on existing nominations by adding emojis to them ^_^
Voting Deadline: Monday, April 11, 2022

More details are available here: https://cd.foundation/cdf-community-awards/

**Comment by erkist** [comment]
Nomination: Andrea Frittoli

Andrea has been a driving force of the CDEvents project since before it was created, and has supported the project both through active leadership, through presentations in several conferences, and through implementation work to integrate CDEvents into other CDF projects. 

Andrea keeps an open mind towards all the different types of interests represented by members of the CDEvents team, and is very open to feedback and suggestions for improving both the project and the CDEvents specification. 

Andrea should win the MVC award for keeping the CDEvents project moving towards a common goal even with busy team members and a lot of need for tough alignment work.

**Comment by afrittoli** [comment]
Nomination: Mauricio Salatino

Mauricio brought CDEvents to life by drafting its initial specification - and that was before the project even had an official name or logo. He created the golang SDK which has been used to date to implement integrations with other projects and proofs of concepts. Mauricio wrote the in and out adapters for Keptn and is now driving support of CDEvents in the Knative projects.

Mauricio should win the MVC award for kickstarting the implementation of CDEvents, for his contributions to the project, his advocacy work and for driving CDEvents adoption in the Keptn and Knative communities.

**Comment by justjenu** [comment]
nomination: Cameron Motevasselani

Cameron has stepped up in the Spinnaker community with a role in the platform SIG among other areas. Cameron is stepping up to help to drive better processes and management in the community - and he does all of this with a great attitude. He's stepped up to help mentor participants in the Google Summer of Code and in working to get access and controls standardized across the community.

He has been an active member in the community for many years on the contributor side as well as on the community side. He has spoken about and evangelized Spinnaker in meetups and across many other events.

Cameron should win this award for the Spinnaker Most Valuable Contributor not only for all that he has done over the years, but most importantly for all that he is doing to help nurture, grow, and reinvigorate the community.

**Comment by e-backmark-ericsson** [comment]
Nomination: Mattias Linnér

Mattias has been active in creating the CDEvents specification from the early days of the events workstream within SIG Interop. He has been contributing to github discussions and provided pull requests both to the protocol and to other areas of the project as well as being highly involved in reviewing PRs written by others. Mattias has helped progressing the CDEvents protocol with an open mind and willingness to share his experience with the rest of us in the project.

**Comment by e-backmark-ericsson** [comment]
There is now a winner for this award, elected by a poll with 50 replies to it, so this issue can be closed.
