### ISSUE TITLE
Backward compatibility strategies

### ISSUE THREAD

**Issue by afrittoli** [cdevents/spec#42]
Many projects and systems already produce and consume CloudEvents.
When a producer starts producing CDEvents in addition to existing CloudEvents, not all consumers may be ready to consume CDEvents.

How to solve this?
1. producers send both CloudEvents and CDEvents
2. producers send CDEvents that are backward compatible with the original CloudEvents and thus can be used by existing consumers as well as new one that may benefit from CDEvents

**Comment by m-linner-ericsson** [comment]
If we look at the picture on https://github.com/cdevents/spec/blob/main/README.md#what-we-provide we are providing our specification on top of CloudEvents. Thus if you have defined your own specification, it will probably clash with CDEvents. I don't think we can cater for all different types of events that exists. I would go for the option of sending both Cloudevents and CDEvents.

**Comment by e-backmark-ericsson** [comment]
I believe we cannot state that CDEvents will be compatible with any existing CloudEvents sent by current tools, so the only feasible way seems to be to recommend to send CDEvents additionally to any current CloudEvents sent by such tools. Eventually those other event could be phased out once the CDEvents are proven to be a valid replacement for them.

**Comment by afrittoli** [comment]
Perhaps we could expand a bit on this in https://cdevents.dev/docs/primer/#relations-to-cloudevents?

`customData` is now implemented, which is one way of handling the part of the data model that do not fit with CDEvents.
The other approach, as @m-linner-ericsson mentioned, is sending multiple events.
