### ISSUE TITLE
Versioning strategies

### ISSUE THREAD

**Issue by afrittoli** [cdevents/spec#43]
Quoting from https://github.com/cdevents/spec/issues/40 (thank you @xibz):

How do you version and support interoperability between all the possibilities?

For instance, some service A could be on version 1, and some service B could be on version 2. Are major versions always going to be backwards compatible, so sending requests between these services should always work?

Further, types have to have a version as well. The `com.github.pull_request.opened` type may have a completely different payload years later. That adds a whole layer of complexity... In addition, adding a new type to the spec would have to be a major version bump of the spec, since anyone using version 1.x and 1.y adds a new type, then 1.x will have no idea on how to deal with that.

How does major versioning look like with interoperability? Does EVERY service need to update to the new major version? How do we plan on handling that???

**Comment by afrittoli** [comment]
We need to have an initial statement on this topic for v0.1 so that it's clear that "v0.1" means

**Comment by afrittoli** [comment]
This is probably a duplicate of #32 :

> Follow up to the discussion in https://github.com/cdevents/spec/pull/30#discussion_r817818324
> We should clarify whether to we want to version events individually or not and what does that mean in terms of compliance to the spec for producers and consumers.

Since this one is included in the roadmap already I would close #32 in favour of this.

**Comment by afrittoli** [comment]
Quoting @m-linner-ericsson comment in #32 so we don't miss it 
https://github.com/cdevents/spec/issues/32#issuecomment-1059115457

> We might want to include something like following text as requirement for the version.

>> MUST be the version of the event/spec used for producing the event

**Comment by m-linner-ericsson** [comment]
When it comes to versioning of the events themselves please also note https://github.com/cloudevents/spec/blob/main/cloudevents/primer.md#versioning-of-cloudevents

**Comment by afrittoli** [comment]
We need at least a basic versioning for the spec. We have https://cdevents.dev/docs/spec/#version for now.
We need a statement about when we need a new version of the spec. This is also needed for the SDK as a reference.

**Comment by e-backmark-ericsson** [comment]
The suggested version for the event, is that intended to match the complete protocol version or is it a specific version for the event type itself? I.e. for CDEvents v0.1 do we intend to give dev.cdevents.artifact.packaged.v0.1 or still dev.cdevents.artifact.packaged.v1, where "v1" represents some specific event type version?

When it comes to whether the version should be part of the type property or not:
When filtering on events it would be easier if there was a separate version field instead of having it as part of the event type. Then you could use filters like:
```
version = 1.0.1
version > 1.0.0
select all version | uniq
```

If it should be part of the type, should it be the whole semantic version of the protocol (or individual event type) or should it just be part of it, i.e,:
```
type = dev.cdevents.artifact.packaged.v0
or type = dev.cdevents.artifact.packaged.v0.1
or type = dev.cdevents.artifact.packaged.v0.1.2
```

**Comment by afrittoli** [comment]
> The suggested version for the event, is that intended to match the complete protocol version or is it a specific version for the event type itself? I.e. for CDEvents v0.1 do we intend to give dev.cdevents.artifact.packaged.v0.1 or still dev.cdevents.artifact.packaged.v1, where "v1" represents some specific event type version?
> 

It is not intended to match the version of the spec. 
If it did, we could simply have the spec version and would not need a version on the events.

If we do use event specific versions, I think that we could have the following situation:

- spec v0.1 (initial state)
  - eventA.v1
  - eventB.v1
  - eventC.V1

- spec v0.2, eventC in changed, eventD is added
  - eventA.v1
  - eventB.v1
  - eventC.V2
  - eventD.v1

- spec v0.3, format of the context is changed, eventE is added
  - eventA.v2
  - eventB.v2
  - eventC.V3
  - eventD.v2
  - eventE.v1

A consequence of this approach is more granularity in versions i.e. if a new spec version introduces no changes in the subset of events that are used by a tool, that tool is not forced to update the SDK to work with producers/consumers that adopted the new spec version. 

An alternative could be to have stage level versions, so that for instance new incident events are added, that has no impact on tools that do not deal if incidents at all, but if a change to any of the event in that stage is made, the entire group of events is updated to a new version. This would reduce the number of versions to maintain.

> When it comes to whether the version should be part of the type property or not: When filtering on events it would be easier if there was a separate version field instead of having it as part of the event type. Then you could use filters like:
> 
> ```
> version = 1.0.1
> version > 1.0.0
> select all version | uniq
> ```

I think there are pros and cons in both cases. 
Having all in one field allow for filtering based a one field, but it also require the filter engine to support regex/startWith or use multiple rules to accept multiple versions of the same event.

> 
> If it should be part of the type, should it be the whole semantic version of the protocol (or individual event type) or should it just be part of it, i.e,:
> 
> ```
> type = dev.cdevents.artifact.packaged.v0
> or type = dev.cdevents.artifact.packaged.v0.1
> or type = dev.cdevents.artifact.packaged.v0.1.2
> ```

If we wanted to use semantic versioning for event versions, what would major and minor versions mean?
We could use minor version for backward compatible changes (optional fields added), and major versions for backward incompatible changes, like fields removed, renamed, new mandatory fields added or structural changes in the context or subject.

**Comment by e-backmark-ericsson** [comment]
Ok. Then I get it. Yes, I'm pro having individual event versions. One reason being the one you mention about being able to notify what events within a new spec version that are actually changed, to make the life easier for the consumers.

I believe we should have semantic versions for the individual events. You state it very well, that a non-backwards compatible change would step the major version and that could be removed or renamed properties.

And the spec version will then more or less just be a grouping of individual event versions, right? What would major.minor.patch on the spec reflect then? Major for removed or renamed events for example? And minor for added events?

If we would have "stage level version" those would behave in a similar way I believe, but I don't think we need to define "stage level" (or "bucket specific"?) versions just yet.

We already have the "version" field in the spec: https://cdevents.dev/docs/spec/#version. The documentation currently says that that is the spec version, but that should probably reflect the individual event version instead then? Otherwise when we step the spec version without changing an individual event, that event's schema won't be correct anymore (if the schema has that field hard coded).

**Comment by afrittoli** [comment]
> Ok. Then I get it. Yes, I'm pro having individual event versions. One reason being the one you mention about being able to notify what events within a new spec version that are actually changed, to make the life easier for the consumers.
> 
> I believe we should have semantic versions for the individual events. You state it very well, that a non-backwards compatible change would step the major version and that could be removed or renamed properties.
💯 

> 
> And the spec version will then more or less just be a grouping of individual event versions, right? What would major.minor.patch on the spec reflect then? Major for removed or renamed events for example? And minor for added events?

👍 

> 
> If we would have "stage level version" those would behave in a similar way I believe, but I don't think we need to define "stage level" (or "bucket specific"?) versions just yet.
> 

👍 

> We already have the "version" field in the spec: https://cdevents.dev/docs/spec/#version. The documentation currently says that that is the spec version, but that should probably reflect the individual event version instead then? Otherwise when we step the spec version without changing an individual event, that event's schema won't be correct anymore (if the schema has that field hard coded).

I think we should still have the spec version in the context.
When tag release `v0.1`, we can set the spec version to `v0.2-wip` on `main`, so that any WIP change to event will temporarily belong to that version. As part of the `v0.2` release, we can change the release version in the schema to `v0.2`.
For events that do not change across releases, we could use the spec version enum to list all valid spec version, and use the latest one as default.

From the example above, in spec `v0.2`, `eventB.v1` would have [`v0.1`, `v0.2`] in the version enum, with `v0.2` as default.
In spec `v0.3`, `eventB.v2` would have [`v0.3`] in the version enum.

**Comment by e-backmark-ericsson** [comment]
Adding a few comments from the somewhat related PR (#61) about json schemas, to not miss these here:
- We should consider hand-editing the schemas, or scripting some adjustments of them, for easier read. For example the "type" field should be listed as the first field within each object for easier read.
- The same way as done on the version field, we could hard code the context.type to its explicit event type within the schema

**Comment by afrittoli** [comment]
From the working group:

>   Proposed starting approach:
>
>        - Version in the context for the spec, free text
>        - Semantic version for events in the event type string

**Comment by afrittoli** [comment]
https://github.com/cdevents/spec/pull/67
