### ISSUE TITLE
Add CDEvents v0.1 terminology to the CDF SIG Interoperability Vocabulary doc

### ISSUE THREAD

**Issue by afrittoli** [cdevents/spec#65]
Add CDEvents v0.1 to the tools terminology [table](https://github.com/cdfoundation/sig-interoperability/blob/main/docs/tools-terminology.md#cicd-tools-and-technologies) in the vocabulary doc.

**Comment by afrittoli** [comment]
Related to #18

**Comment by afrittoli** [comment]
https://github.com/cdfoundation/sig-interoperability/pull/103

**Comment by e-backmark-ericsson** [comment]
The contribution to SIG Interoperability is [there,](https://github.com/cdfoundation/sig-interoperability/pull/103) but not yet merged. It doesn't make sense to let the outstanding merge of that PR hinder the release of CDEvents v0.1, so I'll remove the 0.1 milestone from this issue now.
